### ISSUE TITLE
Google scholar cannot scrawl some of the icml papers

### ISSUE THREAD

**Issue by slowbull** [mlresearch/v80#15]
Hi, 

I am curious about why my paper still does appear on Google search result or Scholar.
For example,   when I search "Decoupled Parallel Backpropagation with Convergence Guarantee", there is no link to http://proceedings.mlr.press/v80/huo18a.html. 

There are also some other papers having the same issue. 

Please help to check the reason. 

Thanks.

**Comment by yuxineverforever** [comment]
same question here. Any solution? @slowbull

**Comment by lawrennd** [comment]
Looks like @Slowbull's paper appears now just fine. somI'll close this and you can open another mentioning your paper.
